import Props from './Properties';

const FieldProperties: any = {
  get(id: string) {
    return this[id] ? this[id] : this['Text'];
  },
  Text: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('placeholder'),
    Props.build('defaultValue'),
    Props.build('hint'),
    Props.build('tabindex'),
    Props.build('ariaLabel'),
    Props.build('validation'),
    Props.build('textTransform'),
    Props.build('protectedValue'),
    Props.build('readonly'),
  ],
  TextArea: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('placeholder'),
    Props.build('defaultValue'),
    Props.build('rows'),
    Props.build('hint'),
    Props.build('tabindex'),
    Props.build('ariaLabel'),
    Props.build('validation'),
    Props.build('textTransform'),
    Props.build('protectedValue'),
    Props.build('readonly'),
  ],
  Checkbox: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),

    Props.build('hint'),
    Props.build('tabindex'),
    Props.build('ariaLabel'),
    Props.build('validation'),
    Props.build('protectedValue'),
    Props.build('checkedDefault'),
    Props.build('readonly'),
  ],
  Datetime: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('dataType'),
    Props.build('defaultDate'),
    Props.build('label'),
    Props.build('hint'),

    Props.build('placeholder'),
    Props.build('ariaLabel'),
    Props.build('validation'),

    Props.build('readonly'),
    Props.build('minDate'),
    Props.build('maxDate'),
  ],
  Dropdown: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),

    Props.build('tabindex'),
    Props.build('placeholder'),
    Props.build('hint'),
    Props.build('ariaLabel'),
    Props.build('options'),
    Props.build('validation'),
    Props.build('protectedValue'),
    Props.build('readonly'),
  ],
  CheckboxGroup: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('tabindex'),
    Props.build('hint'),
    Props.build('ariaLabel'),
    Props.build('options'),
    Props.build('validation'),
    Props.build('protectedValue'),
    Props.build('readonly'),
  ],
  RadioGroup: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('tabindex'),
    Props.build('hint'),
    Props.build('ariaLabel'),
    Props.build('options'),
    Props.build('validation'),
    Props.build('protectedValue'),
    Props.build('readonly'),
  ],
  Grid: [Props.build('type'), Props.build('variable')],
  Image: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('hint'),
    Props.build('alt'),
  ],
  MultipleFile: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('required'),
  ],
  Rating: [Props.build('type'), Props.build('variable')],
  RichText: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('placeholder'),
  ],
  Submit: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('tabindex'),
  ],
  Button: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('tabindex'),
  ],
  Suggest: [
    Props.build('type'),
    Props.build('variable'),
    Props.build('label'),
    Props.build('tabindex'),
    Props.build('placeholder'),
    Props.build('hint'),
    Props.build('ariaLabel'),
    Props.build('options'),
    Props.build('validation'),
    Props.build('protectedValue'),
    Props.build('readonly'),
  ],
  Group: [Props.build('type'), Props.build('variable'), Props.build('label')],
  Label: [
    Props.build('type'),
    Props.build('content'),
    Props.build('ariaLabel'),
    Props.build('hint'),
  ],
  Title: [
    Props.build('type'),
    Props.build('content'),
    Props.build('ariaLabel'),
    Props.build('hint'),
  ],
  Subtitle: [
    Props.build('type'),
    Props.build('content'),
    Props.build('ariaLabel'),
    Props.build('hint'),
  ],
  HorizontalLayout: [Props.build('cols')],
};

export default FieldProperties;
